### ISSUE TITLE
Segmentation fault solved with gcc

### ISSUE THREAD

**Issue by gianlucapettinello** [frealgagu/archlinux.tuxmath#1]
Found on Debian a patch to solve the segmentation fault at the startup.
Attached with .txt suffix

[PKGBUILD.txt](https://github.com/frealgagu/archlinux.tuxmath/files/7189817/PKGBUILD.txt)
[rename-blits-to-tmblits.patch.txt](https://github.com/frealgagu/archlinux.tuxmath/files/7189818/rename-blits-to-tmblits.patch.txt)

**Comment by frealgagu** [comment]
It works fine, thanks. I've updated the package.
