### ISSUE TITLE
No Text in Menues

### ISSUE THREAD

**Issue by coaxx77** [frealgagu/archlinux.tuxmath#2]
There is no text shown in menues. Tried with fresh installed manjaro 21.1.5 (xfc,kde).
![2021-10-15_10-44](https://user-images.githubusercontent.com/35522414/137459248-4fce1632-d2b8-4673-9fa5-b1a34250aab0.jpg)

**Comment by frealgagu** [comment]
Fixed, thanks to @pedroprieto
